version: '3.8'

services:
  postgres:
    image: postgres:14.0
    container_name: hackathon_db
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5545:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: