import { mongoDbClient } from '@/lib/mongo/mongo';
import { generateUUID } from '@/lib/utils';
import { DataStreamWriter, generateObject, tool } from 'ai';
import { Session } from 'next-auth';
import { z } from 'zod';
import { myProvider } from '../models';

interface CreateDocumentProps {
  session: Session;
  dataStream: DataStreamWriter;
}

const sysPrompt = `
You are a MongoDB query and data visualization expert. Your job is to help the user write a MongoDB query to retrieve the data they need. The document schema is as follows:
{
  status: 'LISTED', // This is the status of the properties, we only need to query properties whoses status is 'LISTED'
  transactionType: 'SALE', // This is the type of transaction, the possible values are SALE("acheter") we only support SALE for now. if user ask for rent let him know that we only support SALE for now
  isNew: false, // This is a field to determine whether the property is new or not
  photos: [
    // This photos array contains the photos of the property
    {
      url: 'https://media.yakeey.com/ci001253/image_683059098.jpg',
      subUrl: '/ci001253/image_683059098.jpg',
      isMain: false,
      order: 7,
    },
    {
      url: 'https://media.yakeey.com/ci001253/image_133285652.jpg',
      subUrl: '/ci001253/image_133285652.jpg',
      isMain: false,
      order: 2,
    },
  ],
  address: {
    main: 'Bourgogne rue ennajrani Résidence Sedki',
    street: '',
    neighborhood: 'Bourgogne',
    city: 'Casablanca',
    country: 'Maroc',
    location: [-7.6412489, 33.5967999],
  },
  category: 'FLAT', // This is the category of the property, the possible values are FLAT, VILLA, TERRAIN, OFFICE, COMMERCIAL_BUILDING, currently the only supported types are VILLA and FLAT, if ther user tries to buy something else let him know.
  price: {
    global: 7000, // This is the global price, it is the same field in either rent or buy
    sellerPrice: 7000,
    perSquareMeter: 0,
    currency: 'DH',
    securityDeposit: 16000,
  },
  area: 100, // this is the total surface in square meter
  builtArea: 95, // this is the built surface of the property in square meter
  rooms: 2, // this is the total number of rooms
  floor: 4, // this is flloor of the property
  totalFloors: 5, //this is the total floor of the property
  constructionYear: 1999, // This is the year when the property was constructed
  generalState: 'GOOD', // this is state of the property, these are the possible values NEW, //GOOD, //FAIR, //TO_BE_RENOVATED, //RECENTLY_RENOVATED, //RECENTLY_RESTRUCTURED, //SEMI_FINISHED,
  occupationState: 'EMPTY', // possible values :  EMPTY,OCCUPIED
  bathrooms: 1,
  toilets: 0,
  numberOfFacades: 0,
  directions: [], // These are thre directions of the property   NORTH_EAST, NORTH_WEST, SOUTH_WEST, SOUTH_EAST,
  closedResidence: false,
  accessibility: {
    elevator: true,
    disabledAccess: false,
    intercom: true,
    entryCode: false,
    domotique: false,
    emergencyExit: false,
    serviceDoor: false,
    videoSurveillance: false,
    gatedCommunity: false,
  },
  commonAreas: {
    pool: false,
    playground: false,
    greenSpaces: false,
    gym: false,
    mosque: false,
    hammam: false,
    sportsGround: false,
    bikePath: false,
    multiPurposeHall: false,
    creche: false,
    school: false,
    shoppingCenter: false,
    rooftop: false,
  },
  outDoorSpace: {
    balcony: true,
    terrace: false,
    garden: false,
    privateGarden: false,
    solarium: false,
    privateSwimmingPool: false,
    veranda: false,
  },
  thermalComfort: {
    splitAirConditioning: false,
    centralizedAirConditioning: false,
    splitHeating: false,
    centralizedHeating: false,
    stove: false,
    fireplace: false,
    gasWaterHeater: false,
    electricWaterHeater: true,
    thermalIsolation: false,
  },
  annexes: {
    undergroundParking: true,
    outdoorParking: false,
    box: false,
    basement: false,
    storageSpace: false,
    garage: false,
    undergroundParkingSpaces: 1,
  },
  services: {
    concierge: true,
    janitor: false,
    securityAgent: false,
  },
  kitchen: {
    equipped: true,
    laundryRoom: false,
    americanKitchen: false,
  },
  equipment: {
    wiring: false,
    networkInstallation: false,
    meetingRoom: false,
    lobby: false,
    coldStorage: false,
    extractionSystem: false,
    fiberInstallation: false,
    loadLifter: false,
    curtain: false,
  },
  description:
    "À Casablanca, découvrez cet appartement en location de 95 m², situé au 4ème étage d'un immeuble de 5 niveaux. Il se compose de 2 chambres, 1 salle de bain et dispose d'un balcon pour profiter de l'extérieur. Disponible au prix de 7 000 Dhs, cet espace lumineux et fonctionnel est idéal pour un cadre de vie agréable. Ne manquez pas cette opportunité !",
};


Make sure that your query is case insensitive, and keep in mind that there are typos for example if the user wrote casa he probably means casablanca, of marakish it probably mean marrakech city in morocco...
here is a list of the possible cities that you infer from the input of the user
[
  "Agadir",
  "Soualem",
  "Casablanca",
  "Témara",
  "Marrakech",
  "Rabat",
  "Meknès",
  "Sidi Rahal",
  "Kénitra",
  "Bouznika",
  "Salé",
  "Skhirate",
  "Médiouna",
  "Fès",
  "Tanger",
  "Taghazout-Aourir",
  "Harhoura",
  "El Jadida",
  "Mohammédia",
  "Benslimane",
  "Mehdya",
  "Tétouan",
  "Essaouira",
  "Dar Bouazza",
  "Nouaceur",
  "Azemmour-Haouzia",
  "Béni Mellal",
  "Martil",
  "Ben Guerir",
  "Berrechid",
  "Bni Yakhlef",
  "Dcheira El Jihadia",
  "Errachidia",
  "Fnideq",
  "Khémisset",
  "Larache",
  "Al Hoceima",
  "Khénifra",
  "M'Diq",
  "Ain Harrouda",
  "Safi",
  "Nador",
  "Sefrou",
  "Dakhla",
  "Berkane",
  "Ait Melloul",
  "Tahannaout",
  "Taza",
  "Tiznit",
  "Khouribga",
  "Laâyoune",
  "Ouarzazate",
  "Oujda",
  "Bouskoura",
  "Inezgane",
  "Guelmim",
  "Ifrane",
  "Settat"

  and these are the possible values for the neighborhood
  [
  "Bab Lemrissa",
  "Douar Laaskar",
  "Aeroport Militaire Etat Major",
  "Cap De Mazagan",
  "Dehar El  Kanfoud",
  "Bir Lghazi",
  "Hay Salam Ouislane",
  "Mkinssia",
  "Zone Industrielle Ouled Azzouz",
  "Zone Industrielle Bensouda",
  "Had Soualem (Oulad Abass)",
  "Anza",
  "Sania",
  "Massira I",
  "Chaimae",
  "Targa",
  "Layayda",
  "Had Soualem (Ain Zahra)",
  "Chigaa",
  "Taghazout Bay",
  "Sidi Moumen",
  "Al Hachmia",
  "Hay Amal",
  "Douar Oulad Ben Lmekki",
  "Hay Al Wifaq",
  "Zenagui",
  "Baadi",
  "Burger",
  "Mandarouna",
  "Douar Lawdaya",
  "Oulija",
  "Oued Fes",
  "Al Wifaq 1",
  "Oued Fes Extension",
  "Hay Al Wifaq",
  "Ville Nouvelle",
  "Lotissement Arafat",
  "Les Oudayas",
  "Achakkar",
  "Quartier Industriel De Sidi Ghanem",
  "Hay Riad",
  "Hay Cheikh Mfadel",
  "Tamaraght",
  "Aeroport Menara",
  "Residence Du Golf",
  "Douar Lkoudia",
  "Zone Touristique",
  "Zohour",
  "Assaka",
  "Tildi",
  "Bni Ouriaghel",
  "Chems Agadir",
  "Moulay Rachid",
  "Mimosas",
  "Boubana",
  "Belvedere (Sidi Belyout)",
  "Maghreb Al Arabi",
  "Boukhalef",
  "Fida",
  "Charf",
  "Dhar Mehraz",
  "Cheikh Zaid",
  "Quartier Avenue Des Far",
  "Route De Safi",
  "Sidi Bernoussi",
  "Bouaakaz",
  "Beni Touzine",
  "Hay Mohammadi",
  "Badriouen",
  "11 Janvier",
  "Jardin De La Koutoubia",
  "Hay Al Maghreb Al Arabi",
  "Nouveau Quartier Administratif",
  "Al Maaden - Ain Slim",
  "Yasmina",
  "Lakssour",
  "Inara",
  "Laymoune",
  "Av Moustapha Assayeh",
  "Sidi El Khadir",
  "Bir Rami Ouest",
  "Zone Industrielle Gzenaya",
  "Douar El Magta",
  "Quartier Industriel Doukkarat",
  "Abouab Mhamid",
  "Inchach",
  "Jnane Ad-Dar",
  "Jawhar",
  "Foret Rahrah",
  "Rhabet Zbib",
  "Hay Sidi Boudhar",
  "Lotissement Namssia",
  "Dchar El Aouama",
  "Laabissa",
  "Menzah Rabat",
  "Bettana",
  "Hay Nahda",
  "Golf",
  "Cite Suisse",
  "Mediouna",
  "Ain Amiyer",
  "Liberte",
  "Cite Mohammadi",
  "Les Amicales",
  "Mghayer",
  "Al Farah",
  "Zaytoune",
  "Jbel Kbir",
  "Kasbah",
  "Ouled Ameur",
  "Hay Badr",
  "Ouled Berjal Extension",
  "Atlas-Amelkis",
  "Al Irfane",
  "La Villette",
  "Riyad",
  "Bab Al Bahr",
  "Diour Al Atlas",
  "Hay Agadir",
  "Jebila",
  "Ancienne Medina",
  "Sehrij Gnawa",
  "El Hanae",
  "Saada-Tissir",
  "Ain Chock",
  "Kasbat Nour",
  "Hay Riad",
  "Al Wifaq Lotissement Oum Hani",
  "Zone Industrielle D'El Jadida",
  "Ber Anzaran",
  "Casablanca Marina",
  "Semlalia",
  "Daoudiat",
  "Hay Moulay Ismail",
  "Zouagha",
  "Fes El Jdid",
  "Al Inara",
  "El Mellah",
  "La Ville Haute",
  "Hay Hassani",
  "Bourmana",
  "Hay Al Andalous",
  "Sindibad",
  "Lekrimat",
  "Aaouinat Hajjaj",
  "Hippodrome",
  "Casa Nearshore",
  "Essada",
  "El Manar",
  "Lalla Zahra",
  "Mouilha",
  "Mers Sultan",
  "Hay Salam",
  "M'Hamidi",
  "Tit Mellil (Sidi Hajjaj Oued Hassar)",
  "Hay Hassani",
  "Almaz (Hay Hassani)",
  "Sidi Maarouf",
  "Derb Sultan",
  "Habbous",
  "Derb Lahona",
  "Medina",
  "Mont Fleuri",
  "Jbel Tghat",
  "Ain Noqbi",
  "Almostakbal",
  "Zone Franche De Tanger",
  "Sehb Elward",
  "Nahda Ii",
  "Assam",
  "Afoulki",
  "Al Massira",
  "Hay Inara",
  "Masrour",
  "Hay Atlas",
  "Hay Ghita",
  "Moulay Driss",
  "Medina",
  "Najah",
  "Aazib Abakkiwe",
  "Portes De Marrakech Addoha",
  "Bassatine",
  "Al Mostakbal",
  "Khandagour",
  "Assais - Hay Laarab",
  "Keddan",
  "Port",
  "Les Perles De Bouznika",
  "S.Y.B.A",
  "Beausite",
  "Benmsick",
  "California",
  "Bir Rami Est",
  "Hay Al Amal",
  "Al Khair",
  "Foret Ain Houala",
  "Nkhakhsa",
  "Bir Rami",
  "Harhoura Extension",
  "Takadoum",
  "Hay Azli",
  "Bourgogne (Sidi Belyout)",
  "Ard Daoulla",
  "Oulfa",
  "Hay Mohbakou",
  "Centre Temara",
  "Hay Mohammadi (Ain Sebaa)",
  "Menzeh Saiss",
  "El Ghorba",
  "La Gironde",
  "Les Casernes",
  "Melk Cheikh",
  "Bennani",
  "Jaouhara",
  "El Ghazoua",
  "Ain Sebaa",
  "Hay Charaf",
  "Douar Elberkani",
  "Hay Tazi",
  "Al Adarissa",
  "Bab Jdid",
  "Al Wafa",
  "Safaa",
  "Assaknia",
  "Nahda",
  "Ouled Arfa",
  "Marja",
  "Oued Bou Fekhane",
  "Jnanat",
  "El Mokhfia",
  "Hay Menara",
  "Talaa",
  "Mers Achennad",
  "Hay Mabrouka",
  "Agadir Oufella",
  "Luxus",
  "Centre Ville",
  "Cite Adrar",
  "Bouznika Bay",
  "Quartier Industriel Sidi Brahim",
  "Hay Anas",
  "Hay Al Farah",
  "Kornich Merkala",
  "Marshan",
  "Mujahidine",
  "Hay Ait Skato",
  "Prestigia",
  "Route De Casablanca-Jnanate",
  "Sbata",
  "Narjiss",
  "Sidi Abderrahman Extension",
  "Hay Al Alaouyin",
  "Oulad Mtaa",
  "Hay El Bahja",
  "Sidi Othmane",
  "La Cite",
  "La Cigogne",
  "Al Houzia",
  "Hay Hassani",
  "Lotissement Les Palmiers",
  "Assif",
  "Zone Industrielle Ain Sebaa",
  "Derb Sidi Daoui",
  "Facultes - Route D'El Jadida",
  "Ben Souda",
  "Douar Akkara",
  "Douar Touggana",
  "Anassi",
  "Douar Drabna",
  "Hay Rmal",
  "Ben Debbab",
  "Des Potiers",
  "Errayhan",
  "Quods",
  "Marina",
  "Sable D'Or",
  "Fouarat",
  "Bab Fes",
  "Khabbazat",
  "Haddada",
  "Ismailia",
  "Tiddas",
  "Sidi Messaoud",
  "La Ferraille",
  "Sofia Targa",
  "Route D'Amizmiz",
  "Amerchich",
  "Hssain",
  "Douar Zemrane",
  "Al Hadika",
  "Bouknadel (Ameur)",
  "Jenan Ennahda",
  "Annasr",
  "Sidi Bouzekri",
  "Derb Merrakech",
  "Nouvelle Lahraouyine",
  "Lahraouyine",
  "Gueznaia",
  "Monica",
  "El Bradaa",
  "Hay Moumen",
  "Dyar Dakhama",
  "Zouitina",
  "Zekak Eroumane",
  "Agdal",
  "Quartier Administratif Agdal",
  "Cherkaoui - Marzouka",
  "Ounek Jmel",
  "Les Rosiers",
  "Ain Laatris",
  "Douar Lala Aicha Kerchiya",
  "Sidi Bouzguia",
  "Hay Salam",
  "Tabiaa",
  "Fatima",
  "Mghogha Kbira",
  "Dehar Ahajjam",
  "Al Ouahda",
  "Oulad Yahya",
  "Wifaq",
  "Zone Industrielle Hay Arrahma",
  "Ancienne Medina",
  "Hay Mesk Lil",
  "Oulad Dakak",
  "Al Kamra",
  "L'Ocean",
  "Residence Al Mansour",
  "Hay Al Kora",
  "Touarga",
  "Hay Al Rajaa Fillah",
  "Mozart",
  "Plage Playa Tanger",
  "Fadaat Al Mouhit",
  "Ouled Oujih",
  "Mrabet Charkia",
  "Mrabet 1",
  "Hjilat",
  "El Majd",
  "Mghogha",
  "Bni Said",
  "Complexe Addoha Al Baraka 1",
  "Agdal",
  "Said Hajji",
  "Sala El Jadida",
  "Douar Chouhada",
  "Douar Laataouna",
  "Saleh",
  "Riad Essalam",
  "Cite Imperiale",
  "Ancienne Medina",
  "Zohor Targa",
  "Talborjt",
  "Bouregrag",
  "Hay Rahma",
  "Hay Safae",
  "Pepiniere",
  "Houria",
  "Technopolis",
  "Zarbia",
  "El Hafa",
  "Ganboria",
  "Ville Verte",
  "Ain Maznoud",
  "Koudiat Lahcen",
  "Dehar Laghmich",
  "Playa",
  "Zaidi",
  "Djebel Gueliz",
  "Bouslham",
  "Lkharba",
  "Complexe Panorama 1",
  "La Base Militaire Kenitra",
  "Sayad",
  "Bouskoura",
  "Azzouzia",
  "Rose Maree",
  "Douar Soultan",
  "Lahraouyine Extension",
  "Hay Al Massar",
  "Lagouassam",
  "La Nouvelle Ville Ibn Batouta",
  "El Qaria",
  "Bd De Mohammed Vi",
  "Beni Makada Lakdima",
  "Bir Aharchoun",
  "Ouled Azzouz (Bir El Yamen)",
  "Ahlan",
  "Diour Jamaa",
  "Douar Lhaja Rabat",
  "Guich Oudaya",
  "Zemmouri",
  "Michouar",
  "Haut Agdal",
  "Hay Sinaai Rabat",
  "Oulja",
  "Douar Mhajir",
  "Palais Royal",
  "Mediouna",
  "El Bassatine",
  "Hay Toulal",
  "El Ouarda",
  "Foret  Mrisat",
  "Complexe Doha El Baraka",
  "Douar Al Kortas - Noha",
  "Rte Des Facultes",
  "Boumghit",
  "Soussi",
  "Palmeraie",
  "Haj Mokhtar",
  "Port De Tanger Ville",
  "Bouhout 2",
  "Bir Cheairi",
  "Douar Al Harakat - Plage Rouge",
  "Hamza",
  "Chejirate",
  "Abbadi",
  "Massira Iii",
  "Yasmine",
  "Founty",
  "Sidi Hajjaj Oued Hassar",
  "Al Wifaq 2",
  "Mellah",
  "Essalam",
  "El Kheir",
  "Bouhout 1",
  "Hay Fatima Zohra",
  "Aeroport Tanger Ibn Batouta",
  "Academie Royale Gendarmerie",
  "Chikh Dawi",
  "Douar Sahd",
  "Hay Al Massira Lotissement Al Andalousse",
  "Oulad Mtaa El Gharbiya",
  "Alal El Fassi",
  "Bouargane",
  "Sanaoubar",
  "Dakhla",
  "Riad Salam",
  "Hay Essalam",
  "Plaisance",
  "Gueliz",
  "Douar Al Hana",
  "Koudiat Laabid",
  "Essaada",
  "Palmeraie Extension",
  "Bachkou",
  "Riyad (Tit Mellil)",
  "Dar Essalam (Extension)",
  "Tit Mellil Extension",
  "Mellah",
  "Hay Sidi Baba",
  "Zahwa",
  "Hay Gryou",
  "Al Jawahir",
  "Al Mourabitine",
  "Socoma",
  "Bourgogne (Anfa)",
  "Bin Lkchali",
  "Douar Bouazza",
  "Douar Tounsi",
  "Lissasfa",
  "Ouled Jelal",
  "Lotissement Al Wafaa",
  "Douar Lhaffari",
  "Naim",
  "Hamria",
  "Hay El Hadika",
  "Annour",
  "Route Immouzere",
  "Sidi Amar Hassini Extension",
  "Route De Ouarzazat",
  "Riad Essalam",
  "Hay Oujah Arous",
  "Cap Spartel",
  "Branes 2",
  "Bouskoura (Bir Abdallah)",
  "Cite Militaire",
  "Haut Founty",
  "Kebibat",
  "Amsernate",
  "Iberia",
  "Bir Tamoune",
  "Zone Industrielle Mghogha",
  "El Mechouar Stinia",
  "Boughaz",
  "Ennasser",
  "Hay Zaoudia",
  "Laazifat",
  "Hay Karim Amrani",
  "Douar Haymoud",
  "Hay Hassan Ibn Noamane",
  "Abd Rahman Ben Zidane",
  "Douar Lamzabiyenne",
  "Ben Abid",
  "Sid El Abed",
  "Bas Agdal",
  "Hay Al Amal",
  "Hay Bouhlal",
  "Residence Assabah",
  "Ain Hayat",
  "Tihaouarine",
  "Zone Touristique Ghandouri",
  "Ezzahara",
  "Menzah",
  "M'Sallah",
  "Diour Dokala",
  "Casablanca Finance City",
  "Nahda I",
  "La Seista",
  "Sidi Youssef",
  "Abattoir",
  "Abaraz",
  "Al Houda",
  "Rachidia",
  "Douar Souiri",
  "Ait El Moudden",
  "Ighil Ouderdour",
  "Hay Salim",
  "Jnan El Baraka",
  "Polo (Ain Chok)",
  "Derb El Berkaoui",
  "Ferme Bretonne",
  "Ouled Ahmed",
  "Longchamps",
  "Palmier (Maarif)",
  "Nassim",
  "Kasba",
  "Quartier Du Soleil",
  "Hay Nbichat",
  "Ines-Ilalif-Sanaa",
  "Bouchta-Abdeltif",
  "Masrour Ii",
  "Quartier Oued Eddahab",
  "Quartier Industriel",
  "Taddart",
  "Iligh",
  "La Colline",
  "Al Wafaa",
  "Dakhla Extension",
  "Al Qods",
  "Alsace Loraine",
  "Tilila",
  "Taddarte",
  "Al Osra",
  "Khalil Jabran",
  "Triangle D'Or",
  "Polo (Maarif)",
  "Hopitaux",
  "Ain Borja",
  "Ibn Tachfine",
  "Lido",
  "Lotissement Cherifia",
  "Douar Iziki",
  "Izdihar",
  "Moulay Youssef",
  "Azhar Oulfa",
  "Anfa Superieur",
  "Bab Ighli",
  "Riad Bouskoura",
  "Quartier Bd De Bordeaux",
  "Maarif Extension",
  "Kodiat Ben Driss Al Qods",
  "Californie",
  "Zone Industrielle Ain Chkef",
  "Hay Massira",
  "Bournazil",
  "Roches Noires",
  "Labeta",
  "Lotissement Wilaya De La Region",
  "Al Azhar",
  "Les Portes D'El Aazouzia",
  "Ain Diab Extension 2",
  "Racine",
  "El Hank",
  "Jenan El Ghali",
  "Quartier De Parc Et Place",
  "Aviateur",
  "Quartier Bd Med V",
  "Zone Touristique",
  "Plateau",
  "Californie",
  "Zitoune",
  "Ain Qadous",
  "Boustane Ouislane",
  "Zouagha Bas",
  "Bel Khyat",
  "Hay Mohammadi",
  "Hay El Qods",
  "D.Chriaa",
  "Ain Mechlaoua",
  "Ibnou Rochd",
  "Lotissement Douar Ben Nacer",
  "Skikina",
  "Salam",
  "Tadamoune",
  "Hay Soria",
  "Riad Essalam",
  "Port",
  "Zone Industrielle",
  "Ain Sebaa",
  "Douar Laadem",
  "Douar El Guern",
  "Les Princesses",
  "Tit Mellil",
  "Passadena Village",
  "Najd",
  "Hwawra",
  "Annasr",
  "Mellah",
  "Hay Lalla Soukayna",
  "La Ferraille Esaada",
  "Hay Tghat",
  "Gzoula Sidi Mbarek",
  "Douar Wlad Bouaziz",
  "Hay Essada",
  "Karian Saidia",
  "El Youssoufia",
  "Quartier Des Ambassades",
  "Branes 1",
  "Tamawazna",
  "Chorouk",
  "L'Habitat",
  "Aouama Gharbia",
  "Haddad",
  "Nassim",
  "Al Yousser",
  "Maamora",
  "Al Kawtar",
  "Hay Al Ittissalat",
  "Cite Charaf",
  "Anfa",
  "Haut Anza",
  "Al Inbiaat",
  "La Colline",
  "El Khyam",
  "Aghroud",
  "Errahma",
  "Almaz",
  "El Hajeb",
  "Zone Pepinieres",
  "Ait Taoukte",
  "Eden Island",
  "Hay Amal",
  "Florida - Mandarona",
  "Al Boustane",
  "Tamaris2",
  "Cil",
  "Ain Haroun",
  "Ouled Ziane",
  "Chouhada",
  "Lahouami",
  "Zone Industrielle Sbata",
  "Palmier (Sidi Belyout)",
  "Azhar Oulfa 2",
  "Sidi Abderrahman",
  "Quartier Tsf",
  "Lemkansa",
  "Sidi Abdellah Ghiat",
  "Maarif",
  "Cite Portugaise",
  "Ezzouhour",
  "Hay Salam",
  "Hay Tarik",
  "City Santrime",
  "Al Marja",
  "Sbai",
  "Dhar Lakhmis",
  "Ben Slimane",
  "Ouled Azzouz (Bir El Houssain)",
  "Casabarata",
  "Ain El Hayani",
  "Douar Moussa",
  "El Aouda",
  "Hay Al Firdaous",
  "Quartier Industriel",
  "Rouidate - Majorelle",
  "Boutchakat",
  "Hay Amzile",
  "Nouveau Pole Urbain",
  "Jnan Aourad",
  "El Fadel",
  "Douar Nzala",
  "Issil",
  "Chwiter",
  "Douar Tamasna",
  "Plage Oued Cherrat",
  "Ain Iti",
  "Sidi Abbad",
  "Merchich",
  "Douar Elmejattia Ouled Taleb",
  "Marjane",
  "Ben Mohammed",
  "Californie",
  "Hayt Sghir",
  "Ryad",
  "Hay Nassim",
  "El Menzeh",
  "Riad Ouislane",
  "Douar Ait Lahmad",
  "Sbata",
  "Hay Zerhounia",
  "Hay Essada",
  "Rmilat",
  "Hay Al Massira",
  "Hay Elamal",
  "Oniva",
  "Sidi Amar Hassini",
  "Masterkhouch",
  "Hay Ain Maaza",
  "Jirari",
  "Maamora",
  "Al Wouroud",
  "Playa Blanca",
  "Hay Mouha",
  "Ennahda",
  "Bensergao",
  "Al Fidia",
  "Hay Saada",
  "Rachidia",
  "Akhlij",
  "Oulad Mahjouba",
  "Derb Ghalef",
  "Parc Industriel Cfcim",
  "Derb Al Kabir",
  "Belvedere (Roches Noires)",
  "Fonciere",
  "Derb Omar",
  "Gauthier",
  "Hivernage",
  "Ain Diab",
  "Oasis",
  "Cherifia",
  "Lusitania",
  "Lahraouine (Sidi Othmane)",
  "Aerodrome",
  "Plateau",
  "Oliverie",
  "Hay Al Wafaa",
  "Hay Al Wafae",
  "Nassim",
  "Tamaris1",
  "Akkari",
  "Hay Chabab",
  "Hay Nahda",
  "Quartier Adminitratif",
  "Hay Al Barid",
  "Quartier J5",
  "Ameur",
  "Hay Inbiat",
  "Hay Karima",
  "Zone Industrielle",
  "Hay Wydad",
  "Hay Tanmia",
  "El Fath",
  "Douar Lghouazi",
  "Ryad Skhirate",
  "Lotissement Boueiba",
  "Aguergna",
  "Zaouiya",
  "Igrou Folous",
  "Ibour",
  "Tanger Cite Sportive",
  "Rahrah",
  "Malabata",
  "Mesnana",
  "Gourziana",
  "Azib Lhaj Kaddour",
  "Ennasr",
  "El Khair 2",
  "Lalla Chafia",
  "Castilla",
  "El Farah",
  "Hay Al Wahda",
  "Akrach",
  "Complexe Sportif",
  "Hay El Menzah",
  "Casino",
  "Hay Farah Rabat",
  "Hay Tayaran Rabat",
  "Quartier Industriel Fadila",
  "Souissi",
  "Aviation-Mabella",
  "Abouab Sala",
  "Hay El Fakih Erradi",
  "Roustal",
  "Hay Chmaou",
  "Garden Beach",
  "Bouknadel",
  "Zone Industriel",
  "Zone Industrielle",
  "Had Soualem (Ben Abid)",
  "Toughza",
  "El Hajriyine",
  "Complexe Addoha El Ikhlass",
  "Ahammar",
  "El Mrabet 2",
  "Aouama Zemouri",
  "Essaada",
  "Benkirane",
  "Ziaten",
  "Bir Chiffa",
  "Laaouina",
  "Chat",
  "Beausejour",
  "Beausejour",
  "Mabrouka 3",
  "Hjar Lasfar",
  "Dradeb",
  "Foret Diplomatique",
  "El Krouch",
  "Harrarine",
  "Idrissia",
  "Kasbat",
  "Douar Bouhala",
  "Ouled Hebik",
  "Ben Abid Extension",
  "Harhoura Centre",
  "Forét De Harhoura",
  "Bir Kacem",
  "Douar Doum Rabat",
  "Bouitate",
  "Foret Mayssane Oulad Heriz",
  "Hay Al Fath",
  "Harhoura Lotissement Hassan Ii",
  "Hay Sinaai",
  "Hay Chabab",
  "Quartier Allaymoun",
  "Quartier El Kheir",
  "Dar Essalam",
  "Centre Ville Rabat",
  "Corniche De Rabat",
  "Hay Alqods",
  "Medina",
  "Ain Sidi M'Achou",
  "Plage De Sidi Rahal",
  "Douar Chihna",
  "Hay Imarat",
  "Zone Industrielle",
  "Had Soualem (Douar Gounifid)",
  "Taghazout",
  "Bikhribichin",
  "Aserkit",
  "Anjal",
  "Hassania",
  "Ouled Azzouz (Ain Jemaa)",
  "Lotissement Bethouven",
  "Al Kouass",
  "Nouaceur",
  "Hassan",
  "Hay Ach-Chbanat",
  "Val D'Or",
  "Quartier J3",
  "Riyad Extension",
  "Dar El Lhamra",
  "Hofrat Lakwas",
  "Sehb El Qaid",
  "Sidi Moussa",
  "Sidi Moussa",
  "Tiliwin",
  "Tabriquet",
  "Hay Andalous",
  "Lehouaoura 2",
  "Hay Charaf",
  "Plage De Skhirate",
  "Douar Lhjar",
  "Jawharat Skhirate",
  "Al Bassatine",
  "Ain Rouz",
  "Ilos De Skhirate",
  "Tefrat",
  "Khandeq El Ward",
  "Ain Jdida",
  "Mnar",
  "Tanja Balia",
  "Regaye 3",
  "Bhayer",
  "Regaye 2",
  "Al Amal",
  "Al Amal",
  "Nzaha",
  "Plaza Torro",
  "Ain Jdida",
  "Mghogha Sghira",
  "Essalam 1",
  "Branes Kdima",
  "Fatine",
  "Ben Dibane",
  "Al Manar",
  "Ali Bay",
  "Rif Ii",
  "Complexe Al Moustakbal",
  "Riad Assalam",
  "Ibn Khaldoun",
  "El Mers",
  "Jamila",
  "Marina Bay",
  "Medina Kdima",
  "Rouida",
  "Mojamaa Hassani",
  "Souani",
  "Quartier Administratif",
  "L Al Khair 3",
  "Dar Tounssi",
  "Moualine El Ghaba",
  "Chems El Madina",
  "Hay Al Mohammadi",
  "Hay Assalam - Sofal",
  "Les Chenes",
  "Zone Industrielle Benslimane",
  "Ricoflores",
  "Ferme Ould Nassria",
  "Hay Karim",
  "Foret De Benslimane",
  "Hay El Qods",
  "Lalla Meryem",
  "Hay Nejma",
  "Al Farah",
  "Al Filine",
  "Lotissement Najmat Benslimane",
  "Ain Sferjla",
  "Royal Golf",
  "Hay Al Hassani",
  "Sakhrate Ennemra",
  "Cite Anazha",
  "Hay Adrab",
  "Oasis",
  "Avenue Princesse Lalla Aicha",
  "Hay Nassim",
  "Semsa",
  "Laouzienne",
  "Wikaya",
  "Taboula",
  "Touibla",
  "Korat Sbaa",
  "Dar Zkeik",
  "Kedioua",
  "Tamouda",
  "Al Malaliyenne",
  "Safir",
  "Ain Bou Semllale",
  "Coelma",
  "Boussafou Extension",
  "Bouanan",
  "Zone Industrielle Martil",
  "Torreta",
  "Ziayana",
  "Sania Ramel Airport",
  "Souani",
  "Wilaya",
  "Ain Melloul",
  "Inara",
  "Touabel",
  "Touilaa",
  "Hjar Laaroussi",
  "Tekniya",
  "Saniat Rmel",
  "Jbel Derssa",
  "Sidi Talha",
  "Gherabou",
  "Medina",
  "Kariane",
  "Borj",
  "Boujarah",
  "Boussafou",
  "Jamaa Mezouak",
  "El Ensanche",
  "Barrio",
  "Hamama",
  "Mellah",
  "Mhannech",
  "Taffaline",
  "Sidi Boughaba",
  "Al Amriya",
  "Kasbat El Mehdia",
  "Nouvelle Ville",
  "Azlef",
  "El Menzeh",
  "El Borj",
  "Jrayfat",
  "Des Dunes",
  "Erraounak",
  "Argana",
  "Skala",
  "Kasbah",
  "Ahl Agadir",
  "Medina",
  "Lotissement 4",
  "La Lagune",
  "Frina",
  "Amal",
  "Tafoukte",
  "Boulevard Mohammed V",
  "Errahma",
  "Tamaris1",
  "Ben Abid",
  "Ouled Ahmed",
  "Massay",
  "Rfayef",
  "Quartier Industriel De Safi",
  "Route De Fes",
  "Hay Rami",
  "Sidi Ghouzia",
  "Boutalamine",
  "Hay Assalam",
  "Setti Massaouda",
  "Derb Jdid",
  "Ben Driss",
  "Lotissement Oumnia",
  "Lotissement Samira",
  "Aeroport De Guelmim",
  "Sidi Ahmed Tadli",
  "Sidi Ali Bousserghine",
  "Cite Universitaire",
  "Douar Ouled Lhajja",
  "Terkaa Charkiya",
  "Cite Des Cadres",
  "Amhirich",
  "El Kheir",
  "Hay Al Farah",
  "Sidi Mimoun",
  "El Qouds",
  "Hay Batah",
  "Hay Alouane",
  "Hay Kassam",
  "Hay Al Filaha",
  "Hay El Kamal",
  "Hay Mania",
  "Hay El Mouahiddine",
  "Hay Ibn Rochd",
  "Hay Kasbah",
  "Hay Mabrouka",
  "Hay Qotee Sheikh",
  "Lotissement El Wafa",
  "Les Abattoires",
  "Miftah El Kheir",
  "Hay Massira",
  "Hay Oued Noun",
  "Hay Rzama",
  "Smaala",
  "Hay Raja Fallah",
  "Widadiyat El Irfane",
  "Zone Industrielle De Settat",
  "Hay Sidi El Ghazi",
  "Hay Riad",
  "Hay Tayret",
  "Hay Touaghil",
  "Al Azfa",
  "Bab Sebta",
  "Haidar",
  "Quartier Industriel",
  "Lotissement Zhar",
  "Harbili",
  "Hay Massira",
  "Admin",
  "Al Indimaj",
  "Douar Joualla Sahel",
  "Hay Raja",
  "Jardins Sahel",
  "Lotissement Al Fadl",
  "Sahel Ouled Harriz",
  "Lotissement La Cedre",
  "Lotissement Souk Lakdim",
  "Riyad Sahel",
  "Zone Industrielle Had Soualem",
  "Morro Viejo",
  "Sidi Abid Extension",
  "Assalam",
  "Hay Cham",
  "Ain Jribia",
  "Hay Al Ikhelass",
  "Hay Kinidi",
  "Hay Rachad",
  "Bou Ouzgar",
  "Oulad Lahssan",
  "Bouachra",
  "Cite Annahda",
  "Hay El Fila",
  "Centre Ville",
  "Oulad Mimoun",
  "Hay Nkhilat",
  "Hay Al Amane",
  "Hay Ihssane",
  "Douar El Bared",
  "Rouchdi",
  "Quartier Administratif",
  "Lotissement Ibtissam",
  "Drioua",
  "Douar Ourabiee",
  "Lotissement Al Waheda",
  "Tideft",
  "Lotissement Fadl El Kheir",
  "Zit Al Oulja",
  "Airport Errachidia",
  "Hay Al Karam",
  "Ait Ba Mouha",
  "Boussouf",
  "Ksar Oulitguir",
  "Labita",
  "Caserne Militaire Al Qods",
  "Atlas",
  "Atlas",
  "Hay Fedragoum",
  "Hay El Wahda",
  "Hay Massira",
  "Hay Moulay Rachid",
  "Medina",
  "Ain Bouhechad",
  "Oued Dahab",
  "Boulvard Mohammed Vi",
  "Chaimae Al Zayn",
  "Quartier Administratif",
  "Hay Al Fath",
  "Hay Al Hadiqa",
  "Lotissement Ocean",
  "Kouzahiyat",
  "Lotissement Malak Sahel",
  "Lotissement Al Itkane",
  "Hay Ennasr",
  "Hay Essalam",
  "Zone Industrielle De Beni Mellal",
  "Hay Lalla Meriem",
  "Famille Francaise",
  "Foret Royal",
  "Hay Lalla Hasna",
  "Rhamna",
  "Hay Chabar",
  "Lotissement El Waha",
  "Hay Tennis",
  "Aska",
  "El Massira",
  "Kharej Bab Aglou",
  "Lotissement Hama",
  "Quartier Industriel",
  "Club Onicl",
  "Lotissement Malak",
  "Lotissement Al Amane",
  "Annahda",
  "Douar Si Abass",
  "Douar Rouamcha",
  "Essaada",
  "Haj Abderrahman",
  "Hay Rimal",
  "Ijnnane",
  "Arraha",
  "Al Wahda",
  "Miftah El Kheir",
  "Sidi Abderahman",
  "Derb Daira",
  "Al Massira",
  "Al Montazah",
  "Al Qouds",
  "Asdour",
  "Bin Jradi",
  "Caserne Militaire",
  "Cite Al Mourabitine",
  "Douar El Kheiss",
  "Douar Ayad",
  "Douar Jdid",
  "Essada",
  "Hay Al Wifaq",
  "Haute Taza",
  "Hay El Malha",
  "Lotissement Oum Al Koura",
  "Lotissement Ziad",
  "Hay Doutourga",
  "Hay Al Matar",
  "Lotissement Reda",
  "Foret De Rfayef",
  "La Belle Vue",
  "Lotissement Ennassim",
  "Lotissement Al Kebaj",
  "Douar Des Skouriyines",
  "Slawi",
  "Hay Ryad",
  "Hay Zaytouna",
  "Hay El Nahda",
  "Hay Hassani",
  "Hay Kiliz",
  "Les Jardins",
  "Hay Boukham",
  "Tanmiya",
  "Hay Maamoura",
  "Port De M'Diq",
  "Hay Rttaha",
  "Hay Salam",
  "Tarasste",
  "Lotissement Ait Mzal",
  "Derb Khamiss",
  "Aeroport Militaire De Khouribga",
  "L'Erac",
  "Hay Oued Elmaleh",
  "Lotissement Monssour",
  "Lotissement Monperam",
  "Route De Khemisset",
  "Douar Rekkada",
  "Hay Sidi Boughaba",
  "Ghadira",
  "Hay Riyad",
  "Khandak Zaytoune",
  "Hay Salam",
  "Kondisa",
  "Hay Mansour Dahbi",
  "Agdal",
  "Hay Ain Choufo",
  "Cite Ormvat",
  "Derb Ambasso",
  "La Prairie",
  "Les Jardins D'Ifrane",
  "Oued Tizguit",
  "Hay Al Farah",
  "Public Camping",
  "Lkliaa",
  "Universite Al Akhawaine",
  "El Makasim",
  "Hay El Qods",
  "Hay Charbon",
  "Hay Samara",
  "Jawhara",
  "Nahda",
  "Sidi Yahya",
  "Hay Amlak Bernoussi",
  "Bel Air",
  "Dyar Al Mansour",
  "Hay Dakhela",
  "Paloma",
  "Plage Grand Zenata",
  "Zenata City",
  "Elmouadafin",
  "Agdal",
  "Al Mazar",
  "Ait Oujrar",
  "Argana",
  "Elmoustakbal",
  "Hay El Menzeh",
  "Azrou",
  "Hay Ezzahra",
  "Kasbah El Taher",
  "Quartier Industriel",
  "Hay Massira",
  "Tamazart",
  "Yassmina",
  "Thomo",
  "Lotissement Alia",
  "Aghza Abulay",
  "Barrio Haddou",
  "Boujibar",
  "Cala Bonita",
  "Lotissement Belle Vue",
  "Hay Assalam",
  "Hay Roumane",
  "Hay Sabadia",
  "Marmuca",
  "Mirador Haut",
  "Derkaoui Houmad",
  "Hay Ennour",
  "Sidi Abid",
  "Sidi Mansour",
  "Taghzout",
  "Tighanimine",
  "Boulvard Boujdour",
  "Derb El Feran",
  "Nouvelle Zone Industrielle",
  "El Wifaq",
  "Ancienne Medina",
  "Hay El Amal",
  "Lotissement Ezzahra",
  "Hay Oum Rabie",
  "Lotissement Ben Chakroune",
  "Lotissement Jnane Azemmour",
  "Hanaa 2",
  "Douar El Gharbia",
  "Hay Dakhela",
  "Hay Iqbal",
  "Lotissement Jar El Kheir",
  "Quartier Administratif",
  "Foret Adir",
  "Foret De Haouzia",
  "Foret Pullman",
  "Haouzia",
  "Route Jorf Lasfar",
  "Hay Faraj",
  "Labyoute",
  "Avenue Hassan Ii",
  "Mine Verte",
  "Cite Universitaire",
  "Quartier Industriel",
  "Complexe Culturel 2",
  "Hay Al Amal",
  "Hay Al Jadid",
  "Hay Al Majd",
  "Sbatta",
  "Al Mouna",
  "Hay Al Riyad",
  "Hay Chaibat",
  "Village Ocp",
  "Hay Chabate Al Gharbia",
  "Ancien Quartier",
  "Hay Ennasr",
  "Hay Moulay Rachid",
  "Dior Lhomr",
  "Hay Al Hanaa",
  "Hay Warda",
  "Douar Chikh",
  "Hay Zaouiya Derkaouia",
  "Hay El Ikhae",
  "Hay El Majd",
  "Lotissement Jnane El Kheir",
  "Route Regionale Kelaa",
  "Hay Essalam",
  "Sidi Bouzid",
  "Nouaji",
  "Tamenyarte",
  "Ville Mohamed Vi",
  "Hay Ezzahra",
  "Hay Hakamate",
  "Hay Halima",
  "Hay Lalla Mimouna",
  "Hay L'Erac",
  "Hay Mouloud Akka",
  "Hay Sahrawa",
  "Hay Sarghini",
  "Hay Sqaya",
  "Hay Taddarte",
  "Lotissement Belmiloudi",
  "Lotissement Jnane Zemmour",
  "Hay Ben Seffar",
  "Yasmine",
  "Ahttab",
  "Hay Al Amal",
  "Douar Ouled Jaber",
  "Hay Andalous",
  "Hay Al Qods",
  "Hay Bouhdila",
  "Hay Douar El Mika Zalaka",
  "Hay Mohammadi El Makteb",
  "Hay Hassani",
  "Hay Laymoun",
  "Hay Moukawama",
  "Hay Salem",
  "Lotissement Khaiber",
  "Al Baraka",
  "Al Faraj",
  "Errabii",
  "Lotissement El Omran",
  "Layali",
  "Lotissement El Karam",
  "Lotissement Regraga",
  "Zone Industrielle De Berrechid",
  "Ain Tekki",
  "Al Fath",
  "Diyar Al Alia",
  "Douar Al Mhairchat",
  "Douar Ouled Sidi Azzouz",
  "Amlou Igheriben",
  "Hay Al Filahi",
  "Hay Al Kourss",
  "Hay Assaka",
  "Hay Assalam",
  "Douar Bni Mghid",
  "Hay Hamriya",
  "Hay Nassim",
  "Hay Najd",
  "Hay Pam",
  "Hay Rahma",
  "Hay Tealaouiyen",
  "Lotissement El Ferdaouss",
  "Metchifsane",
  "Zone Industrielle",
  "Al Maghreb Al Jadid",
  "Ancienne Medina",
  "Centre Ville",
  "Douar Ain Chouk",
  "Dyour El Haouata",
  "Foret Olympiqua",
  "Hay Al Manar",
  "Hay El Jadid",
  "Hay Nejma",
  "Douar Lhaj Lamlih",
  "La Ferme Hcika",
  "De La Ferme",
  "Sidi Ahmed Ben Yechou",
  "Zone Industrielle Zenata",
  "Lixus",
  "Aghattas",
  "Lotissement Al Oumrane",
  "Lotissement Chaabane",
  "Cite Al Massira",
  "Zone Industrielle Du Port",
  "Lharch",
  "Zone Industrielle M'Laleh",
  "25 Mars",
  "Aire Industrielle",
  "Al Aaouda",
  "Al Mostakbal",
  "Al Amal",
  "Al Qassam",
  "Al Qods",
  "Al Wahda Bloc D",
  "Hay El Manzah",
  "Al Wifaq",
  "Bd Al Hizam Al Kabir",
  "Diridak",
  "Laayoune Hassan I International Airport",
  "Moulay Rachid",
  "Sidi Buya",
  "Bouzaghlal",
  "El Mhannach",
  "Marina Smir",
  "Restinga",
  "Douar Drao",
  "Amwaj El Jadida",
  "Oued El Firat",
  "Camps El Ghoul - Victor Hugo",
  "Douar Sbai",
  "Hay Al Farah",
  "Hay El Farah",
  "Hay Takkadoum",
  "Avenue Mohamed V",
  "Bouderham1",
  "Zone Industrielle De Taza",
  "Bouderham2",
  "Hay Habbouna",
  "Douar Sidi Abbad",
  "Hay Al Fath",
  "Hay Al Mohammadi",
  "Lotissement Al Andalous",
  "Lotissement Morbiha",
  "Lotissement Wifaq",
  "Hay Sidi Mohamed Oufares",
  "Le Jardin Des Roses",
  "Zone Industrielle",
  "Ait Khassa",
  "Centre Ville",
  "Douar El Hajjar",
  "El Massalah",
  "Douar Hassan Zenata",
  "Hay Al Amal",
  "Plage De Petite Zenata",
  "El Oumrane",
  "El Khattarate",
  "Hay Salam",
  "Iger Azegouagh",
  "Hay Sidi Abdelkarim",
  "Bab El Madina",
  "Sraghna",
  "Lotissement Al Qods",
  "Lotissement Al Baladiya",
  "Tassoumaat",
  "Hay Al Massira",
  "Rhat Rih",
  "Douar Abdeltif Bouhal",
  "Lotissement El Fadl",
  "Hay Haut Ifriquia",
  "Menzah Fedala - Alliances Darna",
  "Hay Dbagha",
  "Oulad Moumen",
  "Hay Essalam",
  "Riad Louizia",
  "Centre Ville",
  "Hay El Massira",
  "Route Louizia",
  "Hay Errachad",
  "Victoria",
  "Hay Fayza",
  "Hay Chams",
  "Hay Mabrouka",
  "Hay La Scierie",
  "Ain Asserdoune",
  "Ait Tisslit",
  "Al Adarissa",
  "Assefet Serhani",
  "Dar Debagh",
  "El Harboulia",
  "El Massira",
  "Tamoumnt",
  "El Massira 2",
  "Hay Al Amria",
  "Hay Atlas",
  "Hay El Houda",
  "Hay Menzah",
  "Jnan Taher",
  "Hay Miftah",
  "La Cite Universitaire",
  "Marina Smir Extension",
  "Laggaichia",
  "Les Oranges",
  "Mghila",
  "Quartier Adminstratif",
  "Riad Salam",
  "Tifrit",
  "Hay El Fath",
  "Tamaris2",
  "Hay Oum Errabia",
  "Oued Rabeh",
  "Hay Al Boustane",
  "Essada",
  "Oulad Botaib",
  "Ben Diban",
  "Oulad Botaib Extension",
  "Cabo Negro",
  "Hay Chaabi",
  "Hay Ahrik",
  "Hay Al Aghrass",
  "Hay Diza",
  "Atlasia",
  "Cite  Faiz",
  "Cite Igroumai",
  "El Jihadiya",
  "Dchiera",
  "Fadesa - Tafoukt",
  "Tassila",
  "Bir Bou Saadi",
  "Hay Mimouna",
  "Al Qods",
  "Cite Universitaire",
  "Ancienne Targa",
  "Cite Amezouj",
  "El Massira",
  "Lotissement Ain Al Ati",
  "Mohit",
  "Lotissement Al Wahda",
  "Hay Sidi Ghrib",
  "Ouled El Haj",
  "Targa",
  "Hay Andalous",
  "Lotissement Oum Kaltoum",
  "Miramar",
  "Alcudia Smir",
  "Biranzarane",
  "Centre Ville",
  "Hay Kasbah",
  "Lotissement Boudass",
  "Ain Zerka",
  "Ancienne Medina",
  "Ennakhil",
  "Hay Afrag",
  "Hay Adregue",
  "Hay Boutini",
  "Hay Rachad",
  "Nahda",
  "Hay Riyad Sidi Boumdine",
  "Lotissement Lalla Moulaty",
  "Tamdroust",
  "Cite Al Akhawaine",
  "Al Madina Al Jadida",
  "Hay Lalla Rkia",
  "Hay Widadiya",
  "Jnane Zitoune",
  "Quartier Industriel De Berkane",
  "Agounaf",
  "Hay El Raha",
  "Hay Tissir",
  "Lotissement Adouz",
  "Lotissement Arsat Chaouia",
  "Bouarouhou",
  "Bouyzazan",
  "Douar Akhandouk",
  "Bades",
  "Berghout",
  "Hay Aarid",
  "Hay Al Matar",
  "Hay Oulad Ibrahim",
  "Anassi",
  "Hay Chaala",
  "Hay Dakhela",
  "Hay Madani",
  "Hay Touima",
  "Issabbanan",
  "Quartier Administratif",
  "Massaoudi",
  "Quartier Militaire",
  "Regolariss",
  "Saquia",
  "Hay Al Hassania",
  "Hay Castour",
  "Aeroport International De Ouarzazate",
  "Bab Ftouh",
  "Lotissement En Phase D'Amenagement",
  "Hay Ait Gdif",
  "Hay Al Qods",
  "Hay Daoud",
  "Hay Isfoutalil",
  "Sidi Daoud",
  "Kasbah Taourirt",
  "Tamassinte",
  "Hanaa 1",
  "Ain Rechaqa",
  "Zone Industrielle Ouarzazate",
  "Hay Annasr Bouachouch",
  "Hay Byad Essoumaa",
  "Ancienne Medina",
  "Takabourt",
  "Centre Ville",
  "Cgi",
  "Drb Essayh",
  "Haj Taoufik",
  "Hay Al Andalous",
  "Hay Al Boustane",
  "Ouled Ayad Ouled Atto",
  "Residence Al Arz",
  "Hay Al Massira",
  "Hay Al Miloud",
  "Hay Assalam",
  "Hay Ben Kirane",
  "Asays",
  "Avenue Al Hoceima",
  "Hay Boudir",
  "Hay Ghar Al Baroud",
  "Hay Gtar",
  "Hay Hassani Berkani",
  "Hay Maghreb Al Arabi",
  "Hay Rjah Fi Allah",
  "Lotissement Al Amane",
  "Hay Mohammadi",
  "Hay Skiker",
  "Hay Takadoum",
  "Hay Tennis",
  "Lazaret",
  "Iris",
  "Jorf Lakhdar",
  "Nour",
  "Reml",
  "Des Oranges",
  "Hay Al Qods",
  "El Massira",
  "Hay Al Batiyo",
  "Riad Isly",
  "Village Koulouch",
  "Hay El Fath",
  "Hay Mabchour",
  "Hay Takaddoum",
  "Village Si Lakhder",
  "Village Touba",
  "Foret De Bouskoura",
  "Village Zerarka",
  "Hay Yassmina",
  "Zitoune",
  "Zone Industrielle Oujda",
  "Lotissement Ennakhil",
  "Achbar",
  "Azib Drai",
  "Bouizate",
  "Chankit",
  "Cooperative 3 Mars",
  "El Massira",
  "Course",
  "Errahma",
  "Hay Anas",
  "Hay Libiar",
  "Hay Bouresas",
  "Hay Ourida",
  "Hay Riyad",
  "Hay Saida",
  "Jerifat",
  "Kaouki",
  "Kariat Chems",
  "Kayjoty",
  "Laarisa",
  "Lamia",
  "Lotissement El Hanaa",
  "La Pergola",
  "Lotissement Marjane",
  "Meftah Arraha",
  "Mestari",
  "Nouvelle Ville",
  "Port De Safi",
  "Sania Zine El Abidine",
  "Sidi Abdelkarim",
  "Azemour",
  "Zaouiya Sidi Wassel",
  "Hay Chawki",
  "Cite Chaaba",
  "Ain El Ghazi",
  "Lotissement Oued Eddahab",
  "Lotissement Safaa",
  "Amouni",
  "Villat",
  "Hay Rass Louta",
  "Hay Mhirez",
  "Lotissement El Menzah"
]

  when it comes to the price of the property, a user might input a fixed number like: 10000DH, i need you to check for greater than 10% of the price and -10% of the price.
  Your response should resprect the following format: "{"$and": [
{// condition 1},
{// condition 2},
]}"
Make sure that your query is case insensitive.
If user add a new criteria, you should add it to the query, beside keeping all the previous criteria.
if this is the initial generated query "'{"$and": [\n' +
      '  {"status": {"$regex": "^LISTED$", "$options": "i"}},\n' +
      '  {"transactionType": {"$regex": "^SALE$", "$options": "i"}},\n' +
      '  {"price.global": {"$gte": 1170000, "$lte": 1430000}}\n' +
      ']}'"
      Then the user ask for address.neighborhood to be added to the query, the new query should be: "{"$and": [\n' +
      '  {"status": {"$regex": "^LISTED$", "$options": "i"}},\n' +
      '  {"transactionType": {"$regex": "^SALE$", "$options": "i"}},\n' +
      '  {"price.global": {"$gte": 1170000, "$lte": 1430000}},\n' +
      '  {"address.neighborhood": {"$regex": "^NEIGHBORHOOD$", "$options": "i"}}\n' +
      ']}"
`;

export const propertyTypes = ['VILLA', 'FLAT'] as const;

export const getProperties = ({
  message,
  dataStream,
}: {
  message: string;
  dataStream: DataStreamWriter;
}) =>
  tool({
    description:
      'Get Suggestions for real estate properties based on user prompt, and make sure to take into consideration the fact that the user can use multiple languages, mainly darija, french and english',
    parameters: z.object({
      price: z.number(),
      propertyType: z.enum(propertyTypes).optional(),
      transactionType: z.enum(['RENT', 'SALE']),
      city: z.string(),
      neighborhood: z.string().optional(),
      bedrooms: z.number().optional(),
      bathrooms: z.number().optional(),
      surface: z.number().optional(),
    }),
    execute: async (res) => {
      const generatedQuery = await generateObject({
        model: myProvider.languageModel('azure'),
        system: sysPrompt,
        prompt: `price: ${res.price}, propertyType: ${res.propertyType}, transactionType: ${res.transactionType}, city: ${res.city}, neighborhood: ${res.neighborhood}, bedrooms: ${res.bedrooms}, bathrooms: ${res.bathrooms}, surface: ${res.surface}. Generate the query necessary to retrieve the data the user wants: ${message}.`,
        schema: z.object({
          query: z.string(),
        }),
      });

      console.log('generatedQuery', generatedQuery);

      const mongoQuery = JSON.parse(generatedQuery.object.query);

      const db = await mongoDbClient.connect();
      const documents = await db
      .db('yakeey_stage')
      .collection('properties')
      .aggregate([
          { $match: mongoQuery },  
          { $sample: { size: 6 } } 
      ])
      .toArray();
      const properties = JSON.parse(JSON.stringify(documents, null, 2));
      const id = generateUUID();

      properties.forEach((property) => {
        property?.photos?.forEach((photo) => {
          if (photo?.url) {
            photo.url = photo.url.replace(
              'media.yakeey.com',
              'medias-stage.yakeey.com'
            );
          }
        });
      });
      
      if (!properties || properties.length === 0) return {};

      return {
        id,
        properties: [...properties],
      };
    },
  });
